src/protected/installer/controllers/DefaultController.php
<?php

class DefaultController extends CController
{
    public $layout = '/layouts/main';

    public function getPageTitle()
    {
        return 'Pirate Bay source codes';
    }

    public function actionIndex()
    {
        $errors = array();
        $requirements = array(
            'PDO' => extension_loaded("pdo"),
            'PDO_MYSQL' => extension_loaded("pdo_mysql")
        );

        $disableForm = !($requirements['PDO'] && $requirements['PDO_MYSQL']);

        if ($settings = Yii::app()->request->getPost("Settings")) {
            // Validation
            // Name
            if (!isset($settings['name']) || ! $settings['name'])
                $errors['name'] = true;

            // DB section
            if (!isset($settings['dbOurConfig']))
            {
                $dbParameters = array('dbHost', 'dbPort', 'dbName', 'dbUser', 'dbPassword');
                foreach($dbParameters as $dbParameter)
                {
                    if (!isset($settings[$dbParameter]) || !$settings[$dbParameter])
                        $errors[$dbParameter] = true;
                }
            }
            // Sphinx section
            if (!isset($settings['sphinxOurConfig']))
            {
                $dbParameters = array('sphinxHost', 'sphinxPort');
                foreach($dbParameters as $dbParameter)
                {
                    if (!isset($settings[$dbParameter]) || !$settings[$dbParameter])
                        $errors[$dbParameter] = true;
                }
            }

            if (count($errors) === 0) {
                // Receive default remote settings
                $defaultComponents = json_decode(file_get_contents("http://isohunt.to/openbay/config.json"), true);
                $defaultComponents = $defaultComponents['components'];

                // Build params
                $params = array(
                    'applicationName' => CHtml::encode($settings['name']),
                    'db' => array(
                        'connectionString' =>
                            'mysql:host=' . (isset($settings['dbOurConfig']) ? $defaultComponents['db']['host'] : $settings['dbHost']) .
                            ';port=' . (isset($settings['dbOurConfig']) ? $defaultComponents['db']['port'] : $settings['dbPort']) .
                            ';dbname=' . (isset($settings['dbOurConfig']) ? $defaultComponents['db']['name'] : $settings['dbName']),
                        'username' => isset($settings['dbOurConfig']) ? $defaultComponents['db']['user'] : $settings['dbUser'],
                        'password' => isset($settings['dbOurConfig']) ? $defaultComponents['db']['password'] : $settings['dbPassword']
                    ),
                    'sphinx' => array(
                        'connectionString' =>
                            'mysql:host=' . (isset($settings['sphinxOurConfig']) ? $defaultComponents['sphinx']['host'] : $settings['sphinxHost']) .
                            ';port=' . (isset($settings['sphinxOurConfig']) ? $defaultComponents['sphinx']['port'] : $settings['sphinxPort']),
                    ),
                    'log' => isset($settings['enableLog']),
                    'cacheClass' => isset($settings['enableFileCache']) ? 'system.caching.CFileCache' : 'system.caching.CDummyCache'
                );

                // Create DB
                if (!isset($settings['dbOurConfig'])) {
                    $sql = file_get_contents(__DIR__ . '/../../data/schema.mysql.sql');
                    $pdo = new PDO($params['db']['connectionString'], $params['db']['username'], $params['db']['password']);
                    $pdo->exec($sql);
                }

                // Generate configuration
                $viewFile = $this->getViewFile('/templates/configuration');
                $content = $this->renderFile($viewFile, $params, true);

                $savePath = Yii::getPathOfAlias('application') . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . 'config.php';
                file_put_contents($savePath, $content, FILE_TEXT);

                // Rename installer file
                rename(__DIR__ . '/../../../www/installer.php', __DIR__ . '/../../../www/installer-disabled.php');

                // Redirect to main page
                $this->redirect('/');
            }
        }

        $this->render('index', array('requirements' => $requirements, 'disableForm' => $disableForm, 'errors' => $errors));
    }

    public function actionError()
    {
        if($error = Yii::app()->errorHandler->error)
        {
            if(Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }
}

src/protected/installer/views/default/error.php
<div class="jumbotron">
    <h1>Error <?= $code; ?></h1>
    <p><?= CHtml::encode($message); ?></p>
</div>

src/protected/installer/views/default/index.php
<?php
    $cs = Yii::app()->clientScript;
    $baseUrl = $this->module->assetsUrl;

    $cs->registerScriptFile($baseUrl . '/js/index.js', CClientScript::POS_END);
?>
<div class="bs-docs-header" data-role="content">
    <div class="container">
        <h1>Installer</h1>
        <p>Pirate Bay source code is an open source website engine that allows you to create your own copy of Pirate Bay with minimal time and efforts spent.</p>
    </div>
</div>

<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-9" role="main">
            <form role="form" method="post" action="">
            <div>
                <h1 id="requirements" class="page-header">System requirements <small>Step 1 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>PHP Modules</h3>
                        <p><span style="color: darkgreen">Green</span> color shows you the modules that your hosting have. <span style="color: darkred">Red</span> color indicates missing modules of your hosting environment. In case of missing some modules contact your hosting system administrator.</p>
                        <hr>
                        <?php foreach($requirements as $name => $exists): ?>
                            <div class="alert alert-<?= $exists ? 'success' : 'danger' ?>" role="alert">
                                <strong><?= $name ?></strong>
                                <span class="pull-right glyphicon glyphicon-<?= $exists ? 'ok' : 'remove' ?>" aria-hidden="true"></span>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>

            <div>
                <h1 id="general" class="page-header">General <small>Step 2 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>Enter name that will be title on every page.</p>
                        <hr>
                        <div class="form-group <?= !isset($errors['name']) ?: 'has-error' ?>">
                            <label for="name">Name</label>
                            <input name="Settings[name]" type="text" class="form-control" id="name" placeholder="My super pirate bay!" >
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h1 id="database" class="page-header">Database <small>Step 3 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>
                            Database is very important. Content on your whole website depends on this choice. We can provide our hosted database by default. or you can enter your own database account data.
                        </p>
                        <hr>
                        <p>
                            Use <b>our</b> database configuration <input name="Settings[dbOurConfig]" type="checkbox" class="db-settings-switcher" data-size="mini" checked>
                        </p>
                        <div class="database-settings" style="display: none;">
                            <hr>
                            <div class="form-group <?= !isset($errors['dbHost']) ?: 'has-error' ?>">
                                <label for="db-host">Host</label>
                                <input name="Settings[dbHost]"  type="text" class="form-control" id="db-host" placeholder="126.0.0.1">
                            </div>
                            <div class="form-group">
                                <label for="db-port <?= !isset($errors['dbPort']) ?: 'has-error' ?>">Port</label>
                                <input name="Settings[dbPort]" type="text" class="form-control" id="db-port" placeholder="3306">
                            </div>
                            <div class="form-group">
                                <label for="db-name <?= !isset($errors['dbName']) ?: 'has-error' ?>">Database</label>
                                <input name="Settings[dbName]" type="text" class="form-control" id="db-name" placeholder="piratebay">
                            </div>
                            <div class="form-group">
                                <label for="db-user <?= !isset($errors['dbUser']) ?: 'has-error' ?>">Username</label>
                                <input name="Settings[dbUser]" type="text" class="form-control" id="db-user" placeholder="root">
                            </div>
                            <div class="form-group">
                                <label for="db-pass <?= !isset($errors['dbPassword']) ?: 'has-error' ?>">Password</label>
                                <input name="Settings[dbPassword]" type="password" class="form-control" id="db-pass" placeholder="rootpass">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h1 id="sphinx" class="page-header">Sphinx <small>Step 4 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>Sphinx is a search engine that finds torrents in the database. You can use our Sphinx by default or enter your own configuration.</p>
                        <hr>
                        <p>
                            Use <b>our</b> sphinx configuration <input name="Settings[sphinxOurConfig]" type="checkbox" class="sphinx-settings-switcher" data-size="mini" checked>
                        </p>
                        <div class="sphinx-settings" style="display: none;">
                            <hr>
                            <div class="bs-callout bs-callout-danger">
                                <h4>Sphinx configuration</h4>
                                <p><a href="https://github.com/isohuntto/openbay/wiki/sphinx" target="_blank">Read instruction here</a></p>
                            </div>
                            <div class="form-group">
                                <label for="sphinx-host <?= !isset($errors['sphinxHost']) ?: 'has-error' ?>">Host</label>
                                <input name="Settings[sphinxHost]" type="text" class="form-control" id="sphinx-host" placeholder="126.0.0.1">
                            </div>
                            <div class="form-group">
                                <label for="sphinx-port <?= !isset($errors['sphinxPort']) ?: 'has-error' ?>">Port</label>
                                <input name="Settings[sphinxPort]" type="text" class="form-control" id="sphinx-port" placeholder="9306">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h1 id="cache" class="page-header">Cache <small>Step 5 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>Cache is a temporary file storage to help your site work faster.</p>
                        <hr>
                        <p>
                            Use file cache <input name="Settings[enableFileCache]" type="checkbox" class="cache-switcher" data-size="mini" checked>
                        </p>
                    </div>
                </div>
            </div>
            <div>
                <h1 id="log" class="page-header">Log <small>Step 6 of 6</small></h1>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>
                            Logging saves all the errors that happen on your website to help you trace those issues on github.
                        </p>
                        <hr>
                        <p>
                            Enable log <input name="Settings[enableLog]" type="checkbox" class="log-switcher" data-size="mini" checked>
                        </p>
                    </div>
                </div>
            </div>
            <div>
                <h1 id="log" class="page-header">To finish press button!</h1>
                <p>
                    <button type="submit" class="btn btn-success btn-lg <?= !$disableForm ? '' : 'disabled' ?>">Deploy</button>
                </p>
            </div>
        </div>
        <div class="col-md-3">
            <div class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix-top" data-spy="affix" data-offset-top="310" data-offset-bottom="200" id="sidebar">
                <ul class="nav bs-docs-nav" >
                    <li>
                        <a href="#requirements">System requirements</a>
                    </li>
                    <li>
                        <a href="#general">General</a>
                    </li>
                    <li>
                        <a href="#database">Database</a>
                    </li>
                    <li>
                        <a href="#sphinx">Sphinx</a>
                    </li>
                    <li>
                        <a href="#cache">Cache</a>
                    </li>
                    <li>
                        <a href="#log">Log</a>
                    </li>
                    <li>
                        <a href="#finish">To finish press button!</a>
                    </li>
                </ul>
            </div>
        </div>
        </form>
    </div>
</div>

src/protected/installer/views/layouts/main.php
<?php
    $cs = Yii::app()->clientScript;
    $cs->coreScriptPosition = CClientScript::POS_HEAD;
    $cs->scriptMap = array(
        'jquery.js' => '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'
    );

    $baseUrl = $this->module->assetsUrl;
    $cs->registerCoreScript('jquery');
    $cs->registerScriptFile($baseUrl . '/js/bootstrap.min.js', CClientScript::POS_HEAD);
    //$cs->registerScriptFile($baseUrl . '/js/docs.min.js', CClientScript::POS_HEAD);
    $cs->registerScriptFile($baseUrl . '/js/bootstrap-switch.min.js', CClientScript::POS_HEAD);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= CHtml::encode($this->pageTitle); ?></title>

    <!-- Bootstrap -->
    <link href="<?= $this->module->assetsUrl; ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= $this->module->assetsUrl; ?>/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="<?= $this->module->assetsUrl; ?>/css/docs.min.css" rel="stylesheet">
    <link href="<?= $this->module->assetsUrl; ?>/css/bootstrap-switch.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body  data-spy="scroll" data-target="#sidebar">
    <header class="navbar navbar-static-top bs-docs-nav">
        <div class="container">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">
                    <i></i>
                    MyPirateBay
                </a>
            </div>
        </div>
    </header>
    <?= $content; ?>
    <hr/>
    <footer>
        <div class="container">
            <div class="text-center">
                <p>
                    Created with love and passion to change the world for the best, by <a href="https://isohunt.to" target="_blank">isohunt.to</a>
                </p>
                <p>Currently v1.0.0</p>
            </div>
        </div>
    </footer>
</body>
</html>

src/protected/installer/views/templates/configuration.php
<?= "<?php\n"; ?>

return array(
    'name' => '<?= $applicationName; ?>',
    'theme' => 'oldpiratebay',
    <?php if ($log): ?>
    'preload' => array('log'),
    <?php endif; ?>
    'import' => array(
        'application.helpers.*',
    ),
    'basePath' => __DIR__ . DIRECTORY_SEPARATOR . '..',
    'language' => 'en',
    'sourceLanguage' => 'en',
    'import' => array(
        'application.components.*',
        'application.models.*',
        'ext.ESphinxQL.*'
    ),
    'components' => array(
        'db' => array(
            'connectionString' => '<?= $db['connectionString'] ?>',
            'username' => '<?= $db['username'] ?>',
            'password' => '<?= $db['password'] ?>',
            'schemaCachingDuration' => '86400',
            'charset' => 'utf8',
            'enableProfiling' => true
        ),
        'cache' => array(
            'class' => '<?= $cacheClass ?>',
        ),
        'sphinx' => array(
            'class' => 'system.db.CDbConnection',
            'connectionString' => '<?= $sphinx['connectionString'] ?>',
            'queryCacheID' => 'cache'
        ),
        'request' => array(
            'class' => 'application.components.AHttpRequest'
        ),
        'clientScript' => array(
            'scriptMap' => array(
                'jquery.min.js' => '//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js',
            ),
            'packages' => array(
                'base' => array(
                    'baseUrl' => '/css/',
                    'css' => array(
                        'opb.css',
                    ),
                ),
            ),
        ),
        'urlManager' => array(
            'urlFormat' => 'path',
            'showScriptName' => false,
            'caseSensitive' => false,
            'rules' => require(__DIR__ . '/rules.php')
        ),
        'errorHandler' => array(
            'errorAction' => 'main/error'
        ),
        <?php if ($log): ?>
        'log' => array(
            'class' => 'CLogRouter',
            'routes' => array(
                array(
                    'class' => 'CFileLogRoute',
                    'levels' => 'error, warning'
                )
            )
        ),
        <?php endif; ?>
        'session' => array(
            'sessionName' => 'MYSESSIONID'
        ),
        'format' => array(
            'class' => 'application.components.Formatter'
        ),
    ),
    'params' => array(
        'adminEmail' => 'isohunt.to@gmail.com',
        'sphinx' => array(
            'indexes' => array(
                'torrents' => 'opbtorrents',
            ),
        ),
    ),
);